HealthCare/Areas/Admin/Controllers/PatientInfoCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthCare.Data;
using HealthCare.Entities;
using Microsoft.CodeAnalysis;

namespace HealthCare.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PatientInfoCRUDController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PatientInfoCRUDController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/PatientInfoCRUD
        public async Task<IActionResult> Index(string userId)
        {
            if (userId != null)
            {
                List<PatientInfo> list = await (from patientInfo in _context.PatientInfo
                                                where patientInfo.userId == userId
                                                select new PatientInfo
                                                {
                                                    patientInfoId = patientInfo.patientInfoId,
                                                    fullName = patientInfo.fullName,
                                                    phoneNumber = patientInfo.phoneNumber,
                                                    birthday = patientInfo.birthday,
                                                    gender = patientInfo.gender,
                                                    insurance = patientInfo.insurance,
                                                    address = patientInfo.address,
                                                    nationalId = patientInfo.nationalId,
                                                    job = patientInfo.job,
                                                    userId = patientInfo.userId,
                                                    meta = patientInfo.meta,
                                                    status = patientInfo.status,
                                                    createAt = patientInfo.createAt,
                                                    updateAt = patientInfo.updateAt
                                                }).ToListAsync();
                ViewBag.userId = userId;

                return View(list);
            }

            return View(await _context.PatientInfo.ToListAsync());
        }


        // GET: Admin/PatientInfoCRUD/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PatientInfo == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.PatientInfo
                .FirstOrDefaultAsync(m => m.patientInfoId == id);
            if (patientInfo == null)
            {
                return NotFound();
            }

            return View(patientInfo);
        }

        // GET: Admin/PatientInfoCRUD/Create
        public IActionResult Create(string userId)
        {
            ViewBag.userId = userId;

            return View();
        }

        // POST: Admin/PatientInfoCRUD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("fullName,phoneNumber,birthday,gender,insurance,address,nationalId,job,userId")] PatientInfo patientInfo)
        {
            if (ModelState.IsValid)
            {
                patientInfo.status = true;
                patientInfo.createAt = DateTime.Now;
                _context.Add(patientInfo);
                if (await _context.SaveChangesAsync() > 0)
                {
                    ModelState.Clear();
                    TempData["msgCreate"] = "Successfully create a new product!";
                    return RedirectToAction(nameof(Index), new { userId = patientInfo.userId });
                }
            }
            return View(patientInfo);
        }

        // GET: Admin/PatientInfoCRUD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PatientInfo == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.PatientInfo.FindAsync(id);
            if (patientInfo == null)
            {
                return NotFound();
            }
            return View(patientInfo);
        }

        // POST: Admin/PatientInfoCRUD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("patientInfoId,fullName,phoneNumber,birthday,gender,insurance,address,nationalId,job,userId,status,createAt")] PatientInfo patientInfo)
        {
            if (id != patientInfo.patientInfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patientInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientInfoExists(patientInfo.patientInfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { userId = patientInfo.userId });
            }
            return View(patientInfo);
        }

        // POST: Admin/PatientInfoCRUD/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.PatientInfo == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PatientInfos'  is null.");
            }
            var patientInfo = await _context.PatientInfo.FindAsync(id);
            if (patientInfo != null)
            {
                _context.PatientInfo.Remove(patientInfo);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }

            return Json(new { success = false });
        }

        private bool PatientInfoExists(int id)
        {
            return (_context.PatientInfo?.Any(e => e.patientInfoId == id)).GetValueOrDefault();
        }
    }
}

HealthCare/Areas/Admin/Views/PatientInfoCRUD/Create.cshtml
@model HealthCare.Entities.PatientInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PatientInfo</h4>
<hr />
@using (Html.BeginForm("Create", "PatientInfoCRUD", FormMethod.Post, new { @id = "form-1" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-4">
            <input type="hidden" asp-for="userId" value="@ViewBag.userId" />

            <div class="form-group">
                <label asp-for="fullName" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="fullName" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="phoneNumber" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="birthday" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="birthday" type="date" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label><small class="text-danger">(*)</small>
                <select class="form-control" id="gender" asp-for="gender">
                    <option value="true">Nam</option>
                    <option value="false">Nữ</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="insurance" class="control-label"></label>
                <input asp-for="insurance" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="address" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nationalId" class="control-label"></label>
                <input asp-for="nationalId" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="job" class="control-label"></label>
                <input asp-for="job" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-green">Create</button>
        <a asp-action="Index" asp-route-userId="@ViewBag.userId" class="btn btn-light">Back to List</a>
    </div>
}

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#fullName'),
            Validator.isRequired('#phoneNumber'),
            Validator.isRequired('#birthday'),
            Validator.isRequired('#address'),
            Validator.isPhone('#phoneNumber')
        ],
    });
</script>

HealthCare/Areas/Admin/Views/PatientInfoCRUD/Details.cshtml
@model HealthCare.Entities.PatientInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PatientInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.insurance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.insurance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nationalId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nationalId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.job)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.job)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.meta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.meta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.createAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.createAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.updateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.updateAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.patientInfoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HealthCare/Areas/Admin/Views/PatientInfoCRUD/Edit.cshtml
@model HealthCare.Entities.PatientInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PatientInfo</h4>
<hr />
@using (Html.BeginForm("Edit", "PatientInfoCRUD", FormMethod.Post, new { @id = "form-1" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="row">
    <div class="col-md-4">
            <input type="hidden" asp-for="patientInfoId" />
            <input type="hidden" asp-for="userId" />
            <input type="hidden" asp-for="createAt">

            <div class="form-group">
                <label asp-for="fullName" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="fullName" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="phoneNumber" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="birthday" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="birthday" type="date" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label><small class="text-danger">(*)</small>
                <select class="form-control" id="gender" asp-for="gender">
                    <option value="true">Nam</option>
                    <option value="false">Nữ</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="insurance" class="control-label"></label>
                <input asp-for="insurance" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label><small class="text-danger">(*)</small>
                <input asp-for="address" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nationalId" class="control-label"></label>
                <input asp-for="nationalId" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="job" class="control-label"></label>
                <input asp-for="job" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group form-check">
                @if (Model.status == true)
                {
                    <input class="form-check-input" type="checkbox" id="status" name="status" value="true" checked>
                }
                else
                {
                    <input class="form-check-input" type="checkbox" id="status" name="status" value="true">
                }
                <label class="form-check-label" for="status">Status</label>
            </div>
            <div class="form-group">
                <label for="createAt" class="control-label">Create At</label>
                <input id="createAt" class="form-control" value="@Model.createAt" disabled />
            </div>
            <div class="form-group">
                <label for="updateAt" class="control-label">Update At</label>
                <input id="updateAt" class="form-control" value="@Model.updateAt" disabled />
            </div>
    </div>
</div>

<div>
    <button type="submit" class="btn btn-green">Save</button>
    <a asp-action="Index" asp-route-userId="@Model.userId" class="btn btn-light">Back to List</a>
</div>
}

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#fullName'),
            Validator.isRequired('#phoneNumber'),
            Validator.isRequired('#birthday'),
            Validator.isRequired('#address'),
            Validator.isPhone('#phoneNumber')
        ],
    });
</script>

HealthCare/Areas/Admin/Views/PatientInfoCRUD/Index.cshtml
@model IEnumerable<HealthCare.Entities.PatientInfo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="a-green" asp-action="Create" asp-route-userId="@ViewBag.userId">Create New</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>STT</th>
            <th>
                @Html.DisplayNameFor(model => model.fullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.updateAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            var i = 1;
            @foreach (var item in Model)
            {
                <tr id="row_@item.patientInfoId">
                    <td class="align-middle">@i</td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.fullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.phoneNumber)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.birthday)
                    </td>
                    @if (item.gender == true)
                    {
                        <td class="align-middle">Nam</td>
                    }
                    else
                    {
                        <td class="align-middle">Nữ</td>
                    }
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.address)
                    </td>
                    <td class="text-center align-middle">
                        @if (item.status == true)
                        {
                            <i class="fa fa-circle text-success font-12" data-toggle="tooltip" data-placement="top" title="Checked"></i>
                        }
                        else
                        {
                            <i class="fa fa-circle text-danger font-12" data-toggle="tooltip" data-placement="top" title="Unchecked"></i>
                        }
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.updateAt)
                    </td>
                    <td class="align-middle">
                        <a asp-action="Edit" asp-route-id="@item.patientInfoId" title="Edit" class="btn btn-outline-warning">
                            <i class="fa-solid fa-pen"></i>
                        </a>
                        <a href="" id="delete" data-id="@item.patientInfoId" title="Delete" class="btn btn-outline-danger">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                        <form asp-action="Delete" id="DeleteForm"></form>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>

@section scripts {
    <script>
        $(document).ready(function () {
            $('body').on('click', '#delete', function () {
                var id = $(this).data("id");
                var antiForgeryToken = $("#DeleteForm input[name='__RequestVerificationToken']").val();
                var conf = confirm("Bạn có muốn xóa bản ghi này không?");

                if (conf == true) {
                    $.ajax({
                        type: 'POST',
                        url: '/Admin/PatientInfoCRUD/Delete',
                        data: {
                            __RequestVerificationToken: antiForgeryToken,
                            id: id
                        },
                        success: function (data) {
                            if (data.success) {
                                $('#row_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
}