HealthCare/Entities/PatientInfo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthCare.Entities
{
    public class PatientInfo
    {
        public int patientInfoId { get; set; }
        [DisplayName("Họ và tên")]
        public string? fullName { get; set;}
        [DisplayName("Số điện thoại")]
        public string? phoneNumber { get; set;}
        [DisplayName("Ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<DateTime> birthday { get; set;}
        [DisplayName("Giới tính")]
        public Nullable<bool> gender { get; set;}
        [DisplayName("BHYT")]
        public string? insurance { get; set;}
        [DisplayName("Địa chỉ")]
        public string? address { get; set;}
        [DisplayName("CMND/CCCD")]
        public string? nationalId { get; set;}
        [DisplayName("Nghề nghiệp")]
        public string? job { get; set; }
        public string? userId { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> status { get; set;}
        public string? meta { get; set;}
        [DisplayName("Ngày tạo")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}")]
        public Nullable<DateTime> createAt { get; set;}
        [DisplayName("Ngày cập nhật")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}")]
        public Nullable<DateTime> updateAt { get; set;} = DateTime.Now;

        [ForeignKey("patientId")]
        public virtual ICollection<Appoiment>? Appoiments { get; set; }
    }
}

HealthCare/Controllers/PatientInfoController.cs
using HealthCare.Data;
using HealthCare.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HealthCare.Controllers
{
    [Authorize(Roles = "Admin, Patient")]
    public class PatientInfoController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public PatientInfoController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);

            if (userId != null)
            {
                List<PatientInfo> list = await (from patientInfo in _context.PatientInfo
                                                where patientInfo.userId == userId
                                                select new PatientInfo
                                                {
                                                    patientInfoId = patientInfo.patientInfoId,
                                                    fullName = patientInfo.fullName,
                                                    phoneNumber = patientInfo.phoneNumber,
                                                    birthday = patientInfo.birthday,
                                                    gender = patientInfo.gender,
                                                    insurance = patientInfo.insurance,
                                                    address = patientInfo.address,
                                                    nationalId = patientInfo.nationalId,
                                                    job = patientInfo.job,
                                                    userId = patientInfo.userId,
                                                    meta = patientInfo.meta,
                                                    status = patientInfo.status,
                                                    createAt = patientInfo.createAt,
                                                    updateAt = patientInfo.updateAt
                                                }).ToListAsync();
                return View(list);
            }

            return RedirectToAction("Login", "UserAuth");
        }

        // GET: Admin/PatientInfoCRUD/Create
        public IActionResult Create()
        {
            var userId = _userManager.GetUserId(HttpContext.User);

            if (userId != null)
            {
                ViewBag.userId = userId;
            }
            return View();
        }

        // POST: Admin/PatientInfoCRUD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("fullName,phoneNumber,birthday,gender,insurance,address,nationalId,job,userId")] PatientInfo patientInfo)
        {
            if (ModelState.IsValid)
            {
                patientInfo.status = true;
                patientInfo.createAt = DateTime.Now;
                _context.Add(patientInfo);
                if (await _context.SaveChangesAsync() > 0)
                {
                    ModelState.Clear();
                    TempData["msgCreate"] = "Successfully create a new product!";
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(patientInfo);
        }

        // GET: Admin/PatientInfoCRUD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PatientInfo == null)
            {
                return NotFound();
            }

            var patientInfo = await _context.PatientInfo.FindAsync(id);
            if (patientInfo == null)
            {
                return NotFound();
            }
            return View(patientInfo);
        }

        // POST: Admin/PatientInfoCRUD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("patientInfoId,fullName,phoneNumber,birthday,gender,insurance,address,nationalId,job,userId,status,createAt")] PatientInfo patientInfo)
        {
            if (id != patientInfo.patientInfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patientInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientInfoExists(patientInfo.patientInfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { userId = patientInfo.userId });
            }
            return View(patientInfo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PatientInfo == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PatientInfos'  is null.");
            }
            var patientInfo = await _context.PatientInfo.FindAsync(id);
            if (patientInfo != null)
            {
                _context.PatientInfo.Remove(patientInfo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientInfoExists(int id)
        {
            return (_context.PatientInfo?.Any(e => e.patientInfoId == id)).GetValueOrDefault();
        }
    }
}

HealthCare/Views/PatientInfo/Create.cshtml
@model HealthCare.Entities.PatientInfo

@{
    ViewData["Title"] = "Tạo hồ sơ bệnh nhân";
}

<div class="container my-5">
    <h1>@ViewData["Title"]</h1>
    <h4>PatientInfo</h4>

    <a class="a-green" asp-controller="Home" asp-action="Index">Trang chủ <i class="fa-solid fa-chevron-right"></i></a>
    <a class="a-green" asp-controller="PatientInfo" asp-action="Index">Hồ sơ bệnh nhân <i class="fa-solid fa-chevron-right"></i></a>
    <span>@ViewData["Title"]</span>
    <hr />

    <div class="row justify-content-center">
        <div class="col-md-8">
            @using (Html.BeginForm("Create", "PatientInfo", FormMethod.Post, new { @id = "form-1" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <input type="hidden" asp-for="userId" value="@ViewBag.userId" />

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="fullName" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="fullName" class="form-control" placeholder="Nguyễn Văn A" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="phoneNumber" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="phoneNumber" class="form-control" placeholder="(+84)xxxxxxxxx" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="birthday" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="birthday" type="date" class="form-control" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="gender" class="control-label"></label><small class="text-danger">(*)</small>
                            <select class="form-control" id="gender" asp-for="gender">
                                <option value="true">Nam</option>
                                <option value="false">Nữ</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="insurance" class="control-label"></label>
                            <input asp-for="insurance" class="form-control" placeholder="Nhập mã bảo hiểm y tế" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="address" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="address" class="form-control" placeholder="Nhập địa chỉ của bạn" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="nationalId" class="control-label"></label>
                            <input asp-for="nationalId" class="form-control" placeholder="Nhập số CMND hoặc CCCD" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="job" class="control-label"></label>
                            <input asp-for="job" class="form-control" placeholder="Nhập nghề nghiệp của bạn" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group text-right">
                            <button type="reset" class="btn btn-light">Nhập lại</button>
                            <button type="submit" class="btn btn-green">Tạo mới</button>
                        </div>
                    </div>
                </div>                
            }
        </div>
    </div>
</div>

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#fullName'),
            Validator.isRequired('#phoneNumber'),
            Validator.isRequired('#birthday'),
            Validator.isRequired('#address'),
            Validator.isPhone('#phoneNumber')
        ],
    });
</script>

HealthCare/Views/PatientInfo/Edit.cshtml
@model HealthCare.Entities.PatientInfo

@{
    ViewData["Title"] = "Cập nhật hồ sơ bệnh nhân";
}

<div class="container my-5"> 
    <h1>@ViewData["Title"]</h1>
    <h4>PatientInfo</h4>

    <a class="a-green" asp-controller="Home" asp-action="Index">Trang chủ <i class="fa-solid fa-chevron-right"></i></a>
    <a class="a-green" asp-controller="PatientInfo" asp-action="Index">Hồ sơ bệnh nhân <i class="fa-solid fa-chevron-right"></i></a>
    <span>@ViewData["Title"]</span>
    <hr />

    <div class="row justify-content-center">
        <div class="col-md-8">
            @using (Html.BeginForm("Edit", "PatientInfo", FormMethod.Post, new { @id = "form-1" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <input type="hidden" asp-for="patientInfoId" />
                <input type="hidden" asp-for="userId" />
                <input type="hidden" asp-for="status" />
                <input type="hidden" asp-for="createAt">

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="fullName" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="fullName" class="form-control" placeholder="Nguyễn Văn A" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="phoneNumber" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="phoneNumber" class="form-control" placeholder="(+84)xxxxxxxxx" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="birthday" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="birthday" type="date" class="form-control" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="gender" class="control-label"></label><small class="text-danger">(*)</small>
                            <select class="form-control" id="gender" asp-for="gender">
                                <option value="true">Nam</option>
                                <option value="false">Nữ</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="insurance" class="control-label"></label>
                            <input asp-for="insurance" class="form-control" placeholder="Nhập mã bảo hiểm y tế" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="address" class="control-label"></label><small class="text-danger">(*)</small>
                            <input asp-for="address" class="form-control" placeholder="Nhập địa chỉ của bạn" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="nationalId" class="control-label"></label>
                            <input asp-for="nationalId" class="form-control" placeholder="Nhập số CMND hoặc CCCD" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="job" class="control-label"></label>
                            <input asp-for="job" class="form-control" placeholder="Nhập nghề nghiệp của bạn" />
                            <span class="form-message text-danger"></span>
                        </div>
                        <div class="form-group text-right">
                            <a class="btn btn-light" asp-action="Index">Quay lại</a>
                            <button type="submit" class="btn btn-green">Cập nhật</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#fullName'),
            Validator.isRequired('#phoneNumber'),
            Validator.isRequired('#birthday'),
            Validator.isRequired('#address'),
            Validator.isPhone('#phoneNumber')
        ],
    });
</script>

HealthCare/Views/PatientInfo/Index.cshtml
@model IEnumerable<HealthCare.Entities.PatientInfo>

@{
    ViewData["Title"] = "Danh sách hồ sơ bệnh nhân";
}

<div class="container my-5">
    <h1>@ViewData["Title"]</h1>

    <p>
        <a class="a-green" asp-action="Create">Thêm hồ sơ</a>
    </p>

    @if (Model != null && Model.Any())
    {
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-6 mb-4">
                    <div class="card border-success">
                        <div class="card-body">
                            <p class="card-text">
                                <i class="fa-solid fa-circle-user"></i>@Html.DisplayNameFor(model => model.fullName):
                                <span class="text-uppercase text-success" style="font-weight:600;">@Html.DisplayFor(modelItem => item.fullName)</span>
                            </p>
                            <p class="card-text"><i class="fa-solid fa-cake-candles"></i>@Html.DisplayNameFor(model => model.birthday): @Html.DisplayFor(modelItem => item.birthday)</p>
                            <p class="card-text"><i class="fa-solid fa-phone"></i>@Html.DisplayNameFor(model => model.phoneNumber): @Html.DisplayFor(modelItem => item.phoneNumber)</p>
                            @if (item.gender == true)
                            {
                                <p class="card-text"><i class="fa-solid fa-venus-mars"></i>@Html.DisplayNameFor(model => model.gender): Nam</p>
                            }
                            else
                            {
                                <p class="card-text"><i class="fa-solid fa-venus-mars"></i>@Html.DisplayNameFor(model => model.gender): Nữ</p>
                            }
                            <p class="card-text"><i class="fa-solid fa-location-dot"></i>@Html.DisplayNameFor(model => model.address): @Html.DisplayFor(modelItem => item.address)</p>
                        </div>
                        <div class="card-footer text-right">
                            <a class="btn btn-light" asp-controller="PatientInfo" asp-action="Edit" asp-route-id="@item.patientInfoId"><i class="fa-solid fa-user-pen"></i>Sửa hồ sơ</a>
                            <a href="#" class="btn btn-light" data-toggle="modal" data-target="#confirmModal"><i class="fa-solid fa-user-xmark"></i>Xóa hồ sơ</a>
                            <a href="#" class="btn btn-light" data-toggle="modal" data-target="#detail_@item.patientInfoId"><i class="fa-solid fa-circle-info"></i>Xem chi tiết</a>
                        </div>
                    </div>

                    <!-- Modal confirm delete -->
                    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Thông báo</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Bạn có chắc muốn xóa hồ sơ bệnh nhân này?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-light" data-dismiss="modal">Đóng</button>
                                    <form asp-action="Delete" asp-route-id="@item.patientInfoId" class="d-inline-block">
                                        <button type="submit" class="btn btn-red">Đồng ý</button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Modal chi tiết-->
                    <div class="modal fade" id="detail_@item.patientInfoId" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header border-bottom-0">
                                    <h5 class="modal-title text-success">Chi tiết hồ sơ</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" style="font-weight:600;">
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-circle-user"></i> @Html.DisplayNameFor(model => model.fullName)</p>
                                        <p class="col-8 text-uppercase text-success" style="font-weight: 800">@Html.DisplayFor(modelItem => item.fullName)</p>
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-cake-candles"></i>@Html.DisplayNameFor(model => model.birthday)</p>
                                        <p class="col-8">@Html.DisplayFor(modelItem => item.birthday)</p>
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-phone"></i>@Html.DisplayNameFor(model => model.phoneNumber)</p>
                                        <p class="col-8">@Html.DisplayFor(modelItem => item.phoneNumber)</p>
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-venus-mars"></i>@Html.DisplayNameFor(model => model.gender)</p>
                                        @if (item.gender == true)
                                        {
                                            <p class="col-8">Nam</p>
                                        }
                                        else
                                        {
                                            <p class="col-8">Nữ</p>
                                        }
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-location-dot"></i>@Html.DisplayNameFor(model => model.address)</p>
                                        <p class="col-8">@Html.DisplayFor(modelItem => item.address)</p>
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-address-card"></i>@Html.DisplayNameFor(model => model.insurance)</p>
                                        @if (item.insurance == "" || item.insurance == null)
                                        {
                                            <p class="col-8">Chưa cập nhật</p>
                                        }
                                        else
                                        {
                                            <p class="col-8">@Html.DisplayFor(modelItem => item.insurance)</p>
                                        }
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-id-card"></i>@Html.DisplayNameFor(model => model.nationalId)</p>
                                        @if (item.nationalId == "" || item.nationalId == null)
                                        {
                                            <p class="col-8">Chưa cập nhật</p>
                                        }
                                        else
                                        {
                                            <p class="col-8">@Html.DisplayFor(modelItem => item.nationalId)</p>
                                        }
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-box-archive"></i>@Html.DisplayNameFor(model => model.job)</p>
                                        @if (item.job == "" || item.job == null)
                                        {
                                            <p class="col-8">Chưa cập nhật</p>
                                        }
                                        else
                                        {
                                            <p class="col-8">@Html.DisplayFor(modelItem => item.job)</p>
                                        }
                                    </div>
                                    <div class="row">
                                        <p class="col-4"><i class="fa-solid fa-calendar-days"></i>@Html.DisplayNameFor(model => model.updateAt)</p>
                                        <p class="col-8">@Html.DisplayFor(modelItem => item.updateAt)</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <div class="text-center">
            <h4 class="text-muted">Bạn chưa có thông tin hồ sơ bệnh nhân</h4>
            <img src="~/img/nofile.png" style="width:50%;"/>
        </div>
        
    }
</div>