HealthCare/Areas/Admin/Controllers/SpecializationCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthCare.Data;
using HealthCare.Entities;
using Microsoft.CodeAnalysis;

namespace HealthCare.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecializationCRUDController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpecializationCRUDController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/SpecializationCRUD?specialtyId=5
        public async Task<IActionResult> Index(int specialtyId)
        {
            if (specialtyId != 0)
            {
                List<Specialization> list = await (from specialization in _context.Specialization
                                                   where specialization.specialtyId == specialtyId
                                                   select new Specialization
                                                   {
                                                       specializationId = specialization.specialtyId,
                                                       specializationName = specialization.specializationName,
                                                       specialtyId = specialtyId,
                                                       order = specialization.order,
                                                       meta = specialization.meta,
                                                       status = specialization.status,
                                                       createAt = specialization.createAt,
                                                       updateAt = specialization.updateAt
                                                   }).ToListAsync();
                ViewBag.specialtyId = specialtyId;

                return View(list);
            }

            return View(await _context.Specialization.ToListAsync());
        }

        // GET: Admin/SpecializationCRUD/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Specialization == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specialization
                .FirstOrDefaultAsync(m => m.specializationId == id);
            if (specialization == null)
            {
                return NotFound();
            }

            return View(specialization);
        }

        // GET: Admin/SpecializationCRUD/Create
        public IActionResult Create(int specialtyId)
        {
            ViewBag.specialtyId = specialtyId;

            return View();
        }

        // POST: Admin/SpecializationCRUD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("specializationName,specialtyId,order,meta")] Specialization specialization)
        {
            if (ModelState.IsValid)
            {
                specialization.status = true;
                specialization.createAt = DateTime.Now;
                _context.Add(specialization);
                if (await _context.SaveChangesAsync() > 0)
                {
                    ModelState.Clear();
                    TempData["msgCreate"] = "Successfully create a new product!";
                    return RedirectToAction(nameof(Index), new { specialtyId = specialization.specialtyId });
                }
            }
            return View(specialization);
        }

        // GET: Admin/SpecializationCRUD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Specialization == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specialization.FindAsync(id);
            if (specialization == null)
            {
                return NotFound();
            }
            return View(specialization);
        }

        // POST: Admin/SpecializationCRUD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("specializationId,specializationName,specialtyId,order,meta,status,createAt")] Specialization specialization)
        {
            if (id != specialization.specializationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specialization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecializationExists(specialization.specializationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { specialtyId = specialization.specialtyId });
            }
            return View(specialization);
        }

        // POST: Admin/SpecializationCRUD/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Specialization == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Specialization'  is null.");
            }
            var specialization = await _context.Specialization.FindAsync(id);
            if (specialization != null)
            {
                _context.Specialization.Remove(specialization);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }

            return Json(new { success = false });
        }

        private bool SpecializationExists(int id)
        {
            return (_context.Specialization?.Any(e => e.specializationId == id)).GetValueOrDefault();
        }
    }
}

HealthCare/Areas/Admin/Views/SpecializationCRUD/Create.cshtml
@model HealthCare.Entities.Specialization

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Specialization</h4>
<hr />
@using (Html.BeginForm("Create", "SpecializationCRUD", FormMethod.Post, new { @id = "form-1" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-4">
            <input type="hidden" asp-for="specialtyId" value="@ViewBag.specialtyId" />

            <div class="form-group">
                <label asp-for="specializationName" class="control-label"></label>
                <input asp-for="specializationName" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="order" class="control-label"></label>
                <input asp-for="order" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="meta" class="control-label"></label>
                <input asp-for="meta" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-green">Create</button>
        <a asp-action="Index" class="btn btn-light">Back to List</a>
    </div>
}

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#specializationName'),
            Validator.isRequired('#order'),
            Validator.isRequired('#meta'),
        ],
    });
</script>

HealthCare/Areas/Admin/Views/SpecializationCRUD/Details.cshtml
@model HealthCare.Entities.Specialization

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Specialization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.specializationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.specializationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.order)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.meta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.meta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.createAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.createAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.updateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.updateAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.specializationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HealthCare/Areas/Admin/Views/SpecializationCRUD/Edit.cshtml
@model HealthCare.Entities.Specialization

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Specialization</h4>
<hr />
@using (Html.BeginForm("Edit", "SpecializationCRUD", FormMethod.Post, new { @id = "form-1" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-4">
            <input type="hidden" asp-for="specializationId" />
            <input type="hidden" asp-for="specialtyId" />
            <input type="hidden" asp-for="createAt" />

            <div class="form-group">
                <label asp-for="specializationName" class="control-label"></label>
                <input asp-for="specializationName" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="order" class="control-label"></label>
                <input asp-for="order" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="meta" class="control-label"></label>
                <input asp-for="meta" class="form-control" />
                <span class="form-message text-danger"></span>
            </div>
            <div class="form-group form-check">
                @if (Model.status == true)
                {
                    <input class="form-check-input" type="checkbox" id="status" name="status" value="true" checked>
                }
                else
                {
                    <input class="form-check-input" type="checkbox" id="status" name="status" value="true">
                }
                <label class="form-check-label" for="status">Status</label>
            </div>
            <div class="form-group">
                <label for="createAt" class="control-label">Create At</label>
                <input id="createAt" class="form-control" value="@Model.createAt" disabled />
            </div>
            <div class="form-group">
                <label for="updateAt" class="control-label">Update At</label>
                <input id="updateAt" class="form-control" value="@Model.updateAt" disabled />
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-green">Save</button>
        <a asp-action="Index" asp-route-specialtyId="@Model.specialtyId" class="btn btn-light">Back to List</a>
    </div>
}

<script src="~/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#specializationName'),
            Validator.isRequired('#order'),
            Validator.isRequired('#meta'),
        ],
    });
</script>

HealthCare/Areas/Admin/Views/SpecializationCRUD/Index.cshtml
@model IEnumerable<HealthCare.Entities.Specialization>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="a-green" asp-action="Create" asp-route-specialtyId="@ViewBag.specialtyId">Create New</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>STT</th>
            <th>
                @Html.DisplayNameFor(model => model.specializationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.order)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.meta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.updateAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            var i = 1;
            @foreach (var item in Model)
            {
                <tr id="row_@item.specializationId">
                    <td class="align-middle">@i</td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.specializationName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.order)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.meta)
                    </td>
                    <td class="text-center align-middle">
                        @if (item.status == true)
                        {
                            <i class="fa fa-circle text-success font-12" data-toggle="tooltip" data-placement="top" title="Checked"></i>
                        }
                        else
                        {
                            <i class="fa fa-circle text-danger font-12" data-toggle="tooltip" data-placement="top" title="Unchecked"></i>
                        }
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.createAt)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.updateAt)
                    </td>
                    <td class="align-middle">
                        <a asp-action="Edit" asp-route-id="@item.specializationId" title="Edit" class="btn btn-outline-warning">
                            <i class="fa-solid fa-pen"></i>
                        </a>
                        <a href="" id="delete" data-id="@item.specializationId" title="Delete" class="btn btn-outline-danger">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                        <form asp-action="Delete" id="DeleteForm"></form>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>

@section scripts {
    <script>
        $(document).ready(function () {
            $('body').on('click', '#delete', function () {
                var id = $(this).data("id");
                var antiForgeryToken = $("#DeleteForm input[name='__RequestVerificationToken']").val();
                var conf = confirm("Bạn có muốn xóa bản ghi này không?");

                if (conf == true) {
                    $.ajax({
                        type: 'POST',
                        url: '/Admin/SpecializationCRUD/Delete',
                        data: {
                            __RequestVerificationToken: antiForgeryToken,
                            id: id
                        },
                        success: function (data) {
                            if (data.success) {
                                $('#row_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
}